import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="hidden lg:flex flex-col">
                    <img id="img-header" className="" src="/assets/desktop/bg-pattern-header.svg" alt=""/>
                    <div className="mr-20 ml-20">
                        <div className="flex flex-row w-full" style={{ marginTop: '-32px'}}>
                            <div className="w-full">
                                <input className="h-16  border w-full rounded-l-lg bg-[#19202D]" type="text" />
                            </div>
                            <div className="w-full">
                                <img src="" alt="" />
                                <input className="h-16 w-full bg-[#19202D]" type="text" />
                            </div>
                            <div className="flex flex-row justify-between min-w-96 items-center pl-3 bg-[#19202D] rounded-r-lg">
                                <input type="checkbox" id="meuCheckbox" className=""/>
                                <label htmlFor="meuCheckbox" className="label-checkbox">Full time only</label>
                                <button className="rounded bg-[#5964E0] h-10 w-28 mr-5">search</button>
                            </div>
                        </div>
                    </div>
                </header>
                {children}
            </body>
        </html>
    );
}
